/**
 * Generates lib/words.ts from the ENABLE word list.
 *
 * Run with: npm run build-words
 *
 * Source: https://norvig.com/ngrams/enable1.txt (Mendel Cooper, public domain).
 * Reads from /tmp/enable3-clean.txt if present, otherwise re-fetches from norvig.com.
 * Applies a small slur blocklist plus an optional project-level lib/blocklist.txt.
 *
 * The ANSWERS export is intentionally kept identical to the current 49-word
 * curated set so the deterministic daily picker (lib/daily.ts) does not shift
 * which word is "today's" puzzle. VALID_GUESSES expands to the full filtered
 * ENABLE list so any real 3-letter word is accepted as a guess.
 */

import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const SLURS = new Set(['abo', 'gyp', 'jew', 'nip', 'wop', 'yid']);

// Existing 49-word answer seed. Keep stable to preserve daily picker output.
// TODO: expand answer set
const ANSWERS_SEED = [
  'cat', 'dog', 'bat', 'hat', 'mat', 'rat', 'sat', 'fat', 'pat', 'tap',
  'top', 'tip', 'pop', 'pup', 'cup', 'cub', 'bud', 'bug', 'bus',
  'run', 'sun', 'fun', 'gun', 'bun', 'nun', 'pun', 'ran', 'man', 'can',
  'ban', 'fan', 'pan', 'tan', 'van', 'dig', 'fig', 'big', 'wig', 'jig',
  'bed', 'red', 'led', 'fed', 'wed', 'box', 'fox', 'mix', 'six', 'fix',
];

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, '..');
const cachedPath = '/tmp/enable3-clean.txt';
const blocklistPath = join(repoRoot, 'lib', 'blocklist.txt');
const outPath = join(repoRoot, 'lib', 'words.ts');

async function loadEnable(): Promise<string[]> {
  if (existsSync(cachedPath)) {
    const raw = readFileSync(cachedPath, 'utf8');
    return raw.split('\n').map((w) => w.trim()).filter(Boolean);
  }
  const res = await fetch('https://norvig.com/ngrams/enable1.txt');
  if (!res.ok) {
    throw new Error(`Failed to fetch enable1.txt: ${res.status}`);
  }
  const raw = await res.text();
  return raw
    .split('\n')
    .map((w) => w.trim().toLowerCase())
    .filter((w) => w.length === 3 && /^[a-z]{3}$/.test(w));
}

function loadBlocklist(): Set<string> {
  if (!existsSync(blocklistPath)) return new Set();
  const raw = readFileSync(blocklistPath, 'utf8');
  return new Set(
    raw
      .split('\n')
      .map((w) => w.trim().toLowerCase())
      .filter(Boolean),
  );
}

function chunk<T>(arr: T[], n: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < arr.length; i += n) out.push(arr.slice(i, i + n));
  return out;
}

function formatLines(words: string[], indent: string): string {
  return chunk(words, 10)
    .map((row) => indent + row.map((w) => `'${w}'`).join(', ') + ',')
    .join('\n');
}

async function main() {
  const candidates = await loadEnable();
  const blocklist = loadBlocklist();

  const filtered = Array.from(
    new Set(
      candidates.filter(
        (w) =>
          w.length === 3 &&
          /^[a-z]{3}$/.test(w) &&
          !SLURS.has(w) &&
          !blocklist.has(w),
      ),
    ),
  ).sort();

  // Sanity: ensure every ANSWERS_SEED word is in the filtered guess pool.
  const seedSet = new Set(ANSWERS_SEED);
  const missing = ANSWERS_SEED.filter((w) => !filtered.includes(w));
  if (missing.length) {
    // Add missing answer words back so guesses always include them.
    for (const w of missing) filtered.push(w);
    filtered.sort();
  }

  const answersDeduped = Array.from(seedSet);

  const header = `// Generated by scripts/build-words.ts. Do not edit by hand.
// Source: ENABLE word list (https://norvig.com/ngrams/enable1.txt, public domain).
// Run \`npm run build-words\` to regenerate.

`;

  const answersBlock = `// TODO: expand answer set
export const ANSWERS: readonly string[] = [
${formatLines(answersDeduped, '  ')}
];
`;

  const guessesBlock = `
const ALL_GUESSES: readonly string[] = [
${formatLines(filtered, '  ')}
];

export const VALID_GUESSES: ReadonlySet<string> = new Set<string>(ALL_GUESSES);

export function isValidGuess(word: string): boolean {
  return VALID_GUESSES.has(word.toLowerCase());
}
`;

  const out = header + answersBlock + guessesBlock;
  writeFileSync(outPath, out, 'utf8');

  console.log(`Wrote ${outPath}`);
  console.log(`  ANSWERS: ${answersDeduped.length}`);
  console.log(`  VALID_GUESSES: ${filtered.length}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
